### ISSUE TITLE
s u s

### ISSUE THREAD

**Issue by Marc92020** [CluckCluckChicken/Magnifier#10]
i found 2 people that are sus
1st is purple
![Screenshot 2021-05-27 1 45 45 PM](https://user-images.githubusercontent.com/75702334/119985565-cc606f80-bf90-11eb-8779-c11e7eb06f35.png)
2nd is a random pig
![119798656-a200aa80-bedb-11eb-93da-d21559857861](https://user-images.githubusercontent.com/75702334/119985653-edc15b80-bf90-11eb-83d8-7b00f6d6ae9e.png)
is there anyone else that is sus? let me know

ban me if you want

**Comment by CluckCluckChicken** [comment]
> is there anyone else that is sus? let me know

red sus

**Comment by Marc92020** [comment]
> > is there anyone else that is sus? let me know
> 
> red sus

okay. O I SAW PURPLE VENT CALL EMERGENCY MEETINGGGGGGGGGG

**Comment by CluckCluckChicken** [comment]
#11 acting kinda sus ngl

**Comment by Marc92020** [comment]
sus
sus
sus
sus
sus
[this project acting sus](https://scratch.mit.edu/projects/537920705/)
