### ISSUE TITLE
Bug:   Magnifier doesnt load

### ISSUE THREAD

**Issue by Quantum-Codes** [CluckCluckChicken/Magnifier#112]
**Describe the bug:**
Magnifier.potatophant.net is stuck on the homepage.  It isn't able to load when after 30 minutes
![20210709_125253](https://user-images.githubusercontent.com/87054411/125161640-2021c380-e1a1-11eb-9684-7def414fc660.jpg)

**To Reproduce:**
Idk... just go to the website? 

**Expected behavior:**
Load within 5 secs

**Browser Information:**
Latest updated Android OS on my Samsung tab(not too old. Like 2 years now). Browser: chrome (also latest updated)

**Additional context:**
Screenshot above.
It loaded before (when I was the first 50 users of this site.) I only visited once. After a month(or 2 or 3), this won't load

**Comment by CluckCluckChicken** [comment]
This is an issue with your setup, not magnifier. Clear you cache and make sure your browser is configure to use WebAsembly.

**Comment by Quantum-Codes** [comment]
Sorry, I cant.... chrome warns me:

WARNING: EXPERIMENTAL FEATURES AHEAD! By enabling these features, you could lose browser data or compromise your security or privacy. Enabled features apply to all users of this browser.

**Comment by CluckCluckChicken** [comment]
> Sorry, I cant.... chrome warns me:
> 
> WARNING: EXPERIMENTAL FEATURES AHEAD! By enabling these features, you could lose browser data or compromise your security or privacy. Enabled features apply to all users of this browser.
> 
> Written in chrome://flags

wasm should be enabled by default in the latest version of chrome, so make sure it's updated then enable it anyway. magnifier can't run without it.

**Comment by Quantum-Codes** [comment]
Ok. So which one? There are 3

**Comment by CluckCluckChicken** [comment]
> Ok. So which one? There are 3

3 flags?

**Comment by Quantum-Codes** [comment]
![Screenshot_20210712-131550_Chrome](https://user-images.githubusercontent.com/87054411/125249899-52ebc900-e313-11eb-965b-20692302228a.jpg)

**Comment by Quantum-Codes** [comment]
Which one? I see some are default too

**Comment by CluckCluckChicken** [comment]
> ![Screenshot_20210712-131550_Chrome](https://user-images.githubusercontent.com/87054411/125249899-52ebc900-e313-11eb-965b-20692302228a.jpg)
> webassembly tiring is also default (saying cuz its not shown fully in the ss)

maybe you should try experimental webassembly? also mobiles are weird and don't always like to cooperate (although it works on my phone and a decent proportion of magnifier's userbase use mobiles according to analytics), try on a pc?

**Comment by Quantum-Codes** [comment]
Doesn't work. chrome://flags/#enable-experimental-webassembly-features can u say wht u did

**Comment by CluckCluckChicken** [comment]
> Doesn't work. chrome://flags/#enable-experimental-webassembly-features can u say wht u did

i didn't do anything, something is definitely wrong with your setup.

**Comment by Quantum-Codes** [comment]
Pretty weird. I never touched the flag thing after my first login. And it used to work

**Comment by Quantum-Codes** [comment]
Not working even after software update.

Can u give me API to get user comments?

**Comment by Quantum-Codes** [comment]
@CluckCluckChicken  what API u used to get profile comments? 
I heard there is  a magnifier API too?

**Comment by Quantum-Codes** [comment]
@CluckCluckChicken  IT WORKS YEEEEEES

**Comment by Quantum-Codes** [comment]
I'm banned. I can't login.... RIP...... :(

**Comment by Quantum-Codes** [comment]
@CluckCluckChicken   again broke. But not like last time. Homepage loads, browse page loads, but I can't browse a user.... even adding   /users/(username) it just keeps loading (top bar loads tho)

**Comment by CluckCluckChicken** [comment]
> @CluckCluckChicken again broke. But not like last time. Homepage loads, browse page loads, but I can't browse a user.... even adding /users/(username) it just keeps loading (top bar loads tho)

something weird happened with the server the api is running on and i ran out of mobile data on holiday so i couldnt do anything. it should all be back up now.

**Comment by Quantum-Codes** [comment]
Ok, it's working! Yesterday the site-api of Scratch also wasn't updating new comments...

**Comment by pikachub2005** [comment]
Tries using magnifier: just says "seeing if <type> exists..." and never loads
Tries using the api:
![Screenshot 2021-10-08 11 48 32 AM](https://user-images.githubusercontent.com/74213212/136586463-9e3673d7-00d1-4058-b838-ae0d53feacc7.png)

**Comment by davwat** [comment]
> Tries using magnifier: just says "seeing if exists..." and never loads Tries using the api: ![Screenshot 2021-10-08 11 48 32 AM](https://user-images.githubusercontent.com/74213212/136586463-9e3673d7-00d1-4058-b838-ae0d53feacc7.png)

this doesn't happen for me.

**Comment by pikachub2005** [comment]
idk it's weird
