### ISSUE TITLE
I would like to speak to the manager

### ISSUE THREAD

**Issue by lnsanityGames** [CluckCluckChicken/Magnifier#12]
There is no discussion section.
That is not poggers, and also very sus of you not to introduce section to separate memes and suggestions.

**Comment by CluckCluckChicken** [comment]
[better?](https://github.com/CluckCluckChicken/Magnifier/discussions/13)

**Comment by Quantum-Codes** [comment]
> [better?](https://github.com/CluckCluckChicken/Magnifier/discussions)

Gone... more _sus_
