### ISSUE TITLE
sus

### ISSUE THREAD

**Issue by JackyBorderCollie** [CluckCluckChicken/Magnifier#2]
this image is sus as an imposter:
![](https://cdn1.iconfinder.com/data/icons/logos-brands-in-colors/231/among-us-player-red-512.png)

**Comment by CluckCluckChicken** [comment]
among us

**Comment by brourbeinsus** [comment]
amogus

**Comment by CluckCluckChicken** [comment]
i found the imposter we can safely close this without being sabotage reactor

**Comment by CluckCluckChicken** [comment]
yey we did 50% of become epic gamer milestone!!11!!1!

**Comment by JackyBorderCollie** [comment]
no pls open it

**Comment by CluckCluckChicken** [comment]
ok sus reactivated

**Comment by CluckCluckChicken** [comment]
but in order to become epic gamers this and #1 need to be closed at some point

**Comment by JackyBorderCollie** [comment]
ok ima close it we need to be epic gamers 😎

**Comment by JackyBorderCollie** [comment]
impostor closed this
