### ISSUE TITLE
Amogoose

### ISSUE THREAD

**Issue by PoIygon** [CluckCluckChicken/Magnifier#3]
Sussy sus sus postor right at the sus elecrical!!!1!1!1!!1!2!

**Comment by CluckCluckChicken** [comment]
omg they **VENT** in the suss electrical!!!1!!11! sussy imposter

**Comment by PoIygon** [comment]
EMRGENCHY MEECHING

**Comment by CluckCluckChicken** [comment]
WHOS OIN THE NAVGATION VENT????

**Comment by JackyBorderCollie** [comment]
OMG VENT I SAW THEM VENT HERE IS PROOF:
![](https://u.cubeupload.com/JackyBorderCollie/vent.png)

**Comment by JackyBorderCollie** [comment]
ok maybe the proof is low quality BUT STILL I SAW THEM VENT!!!

**Comment by CluckCluckChicken** [comment]
OMG VENT BROWN

**Comment by CluckCluckChicken** [comment]
**scratch addons** omg i said it

**Comment by brourbeinsus** [comment]
> **scratch addons** omg i said it

nono word aaaa

**Comment by FunctionalMetatable** [comment]
> **scratch addons** omg i said it

*screams*

**Comment by CluckCluckChicken** [comment]
> OMG VENT I SAW THEM VENT HERE IS PROOF:
> ![](https://camo.githubusercontent.com/b75fc05ca912d136ba625ba6a2f1b9d7b1ee9aacdb2dfffe2d5de3ff2f7f2d92/68747470733a2f2f752e6375626575706c6f61642e636f6d2f4a61636b79426f72646572436f6c6c69652f76656e742e706e67)

but is that the navigation or SHIELD VENT??/??//?/?//

**Comment by CluckCluckChicken** [comment]
kinda sus bro

**Comment by CluckCluckChicken** [comment]
[sad](https://scratch.mit.edu/discuss/topic/489569/?page=15#post-5280721)

**Comment by JackyBorderCollie** [comment]
ok let's vote brown and close issue wE nEeD tO bEcOmE ePiC gAmErS!!!!11111!!!!!!111!!!!!!!!

**Comment by CluckCluckChicken** [comment]
brown sus

**Comment by CluckCluckChicken** [comment]
vote rocket on [this](https://github.com/CluckCluckChicken/Magnifier/issues/3#issuecomment-848899033) to eject the sussy imposter"!!1
