### ISSUE TITLE
we will never become EPIC GAMER at this rate!!!1111!!

### ISSUE THREAD

**Issue by CluckCluckChicken** [CluckCluckChicken/Magnifier#4]
sad

**Comment by return-misaPuding** [comment]
I believe we will, *especially because of the SEO optimization* . Also,
@potatophant , is @CluckCluckChicken your alt acc?

Dne út 25. 5. 2021 23:31 uživatel potatophant ***@***.***>
napsal:

**Comment by CluckCluckChicken** [comment]
same account

**Comment by return-misaPuding** [comment]
Wdym?

Dne st 26. 5. 2021 8:31 uživatel potatophant ***@***.***>
napsal:

**Comment by CluckCluckChicken** [comment]
display name is potatophant, username cluckcluckchicken

**Comment by JackyBorderCollie** [comment]
RIP only few part of milestone complete

**Comment by CluckCluckChicken** [comment]
lets become 50% epic gamer by doing this:

**Comment by JackyBorderCollie** [comment]
OHHHHHHHHHHHHHHH YES ONLY ONE ISSUE LEFT AND WE'LL BE EPIC GAMERSSSSSSSSSS

**Comment by JackyBorderCollie** [comment]
YES WE BECAME EPIC GAMERSSSSSSSSSSSS!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!11!1!!1!1!1!!!

**Comment by CluckCluckChicken** [comment]
epic pog !!1!1111 we are eipc gamers

**Comment by brourbeinsus** [comment]
YES
