### ISSUE TITLE
Bug: magnifier not releasing

### ISSUE THREAD

**Issue by JackyBorderCollie** [CluckCluckChicken/Magnifier#46]
**Describe the bug**

OMG it's the day that magnifier needs to be released but it's not releasing!!! (also i'm in slovak so there's a different timezone) here's a screenshot:

![](https://u.cubeupload.com/JackyBorderCollie/susususus.png)

as you can see it's very sussy!!!!11!1!1!!!

**To Reproduce**

release it

**Expected behavior**

should be released

**Browser Information**

chrome

**Additional context**

sus

**Comment by return-misaPuding** [comment]
This is very sussy if magnifier won´t say where he was then it´s probably the impostor!!!111!!11!

**Comment by CluckCluckChicken** [comment]
ngl kinda sus

**Comment by CluckCluckChicken** [comment]
magnifier is stuck in the vents im trying to get it out

**Comment by return-misaPuding** [comment]
> 
> 
> magnifier is stuck in the vents im trying to get it out

Waaaaaaaaait magnifier is in the vents it must be da imposter add da "sus" label!!!111!!1!

**Comment by JackyBorderCollie** [comment]
omg this sussy get it out the vents pleaseee and vote out the imposte- wait when potatophant is trying to get it out tHeN hE mIgHt bE tHe sUsSy iMpOsTeR!!1!!!1!1!!1!!!

**Comment by JackyBorderCollie** [comment]
oMg tHe sUsSy lAbEl hAs bEeN aDdEd!11!11!!!

**Comment by return-misaPuding** [comment]
> 
> 
> omg this sussy get it out the vents pleaseee and vote out the imposte- wait when potatophant is trying to get it out tHeN hE mIgHt bE tHe sUsSy iMpOsTeR!!1!!!1!1!!1!!!

Oh YuP yUp AlSo VoTe WiTh ThE rOcKeT eMoJi [https://github.com/CluckCluckChicken/Magnifier/issues/46#issuecomment-850967295](HeRe) To EjEcT tHeSe SuSsY iMpOsTeRs!!!111!!1!

**Comment by JackyBorderCollie** [comment]
very sussy

**Comment by Marc92020** [comment]
Magnifier is very sus.
is it on the webstore or is it in susland?

**Comment by FunctionalMetatable** [comment]
Duplicate of #42

**Comment by CluckCluckChicken** [comment]
magnifier is released time to close this!
