### ISSUE TITLE
extra challenge

### ISSUE THREAD

**Issue by JackyBorderCollie** [CluckCluckChicken/Magnifier#5]
the final challenge before we become epik gamers pLeAsE aDd iT tO tHe ePiC gAmErS mIlEsToNe!!1!1

also find who is sus and vote him

**Comment by CluckCluckChicken** [comment]
omg 3am imposter call challenge prank gone wrong cops called!!1!!1

**Comment by brourbeinsus** [comment]
![AA1E3340-E5B1-4886-AD9C-127937C3FC38](https://user-images.githubusercontent.com/79854224/119749194-9756fe80-be64-11eb-954c-2a500f3b1ab6.jpeg)
 
 omgggg **_EMERGENCY MEETING_** red venteddddddd he is omega sussy impostor!!1!!1!!!!1!! :O

**Comment by CST1229** [comment]
react 🚀 on [this poæst](https://github.com/CluckCluckChicken/Magnifier/issues/5#issuecomment-849227193) to eject the omega sussy impostor!!11!1441!four!

**Comment by CluckCluckChicken** [comment]
red sus 😂😂😂 🚀 EJECT THE 🔪imposter🔪 and deactivate the 😳sussy😳 among us!!111!!11

**Comment by CST1229** [comment]
![sussy](https://user-images.githubusercontent.com/68464103/119798656-a200aa80-bedb-11eb-93da-d21559857861.png)

**Comment by JackyBorderCollie** [comment]
VOTE RED HE IS ALWAYS SUS THE MEMES SAY IT

**Comment by JackyBorderCollie** [comment]
_JackyBorderCollie voted Red._

**Comment by CluckCluckChicken** [comment]
red sussy big chungus imposter!!1!11!

**Comment by JackyBorderCollie** [comment]
ok lets vote out the red impostor and close

**Comment by CST1229** [comment]
what about the white imposter?

**Comment by JackyBorderCollie** [comment]
white is clear white is not imposter

**Comment by CST1229** [comment]
k then he was sus but he isn't

**Comment by Marc92020** [comment]
s u s
![Screenshot 2021-05-27 1 45 45 PM](https://user-images.githubusercontent.com/75702334/119872832-e434e680-bef1-11eb-875f-f1597bc995b2.png)
boi dat guy is sus
wait that is purple
purple sus

**Comment by JackyBorderCollie** [comment]
OMG 2 imposters found les close dis
