### ISSUE TITLE
Bug: Replace localhost:5001 to api.magnifier.potatophant.net

### ISSUE THREAD

**Issue by FunctionalMetatable** [CluckCluckChicken/Magnifier#54]
https://github.com/CluckCluckChicken/Magnifier/blob/4a0d26c281946c19bee191ccc86ba3f27d7ee333/Spyglass/Pages/Browse.razor#L57

https://github.com/CluckCluckChicken/Magnifier/blob/4a0d26c281946c19bee191ccc86ba3f27d7ee333/Spyglass/Pages/Browse.razor#L73

https://github.com/CluckCluckChicken/Magnifier/blob/4a0d26c281946c19bee191ccc86ba3f27d7ee333/Spyglass/Pages/Browse.razor#L89

https://github.com/CluckCluckChicken/Magnifier/blob/4a0d26c281946c19bee191ccc86ba3f27d7ee333/Spyglass/Pages/Login.razor#L38

https://github.com/CluckCluckChicken/Magnifier/blob/4a0d26c281946c19bee191ccc86ba3f27d7ee333/Spyglass/Pages/ViewProfile.razor#L68

https://github.com/CluckCluckChicken/Magnifier/blob/4a0d26c281946c19bee191ccc86ba3f27d7ee333/Spyglass/Pages/ViewProfile.razor#L85

https://github.com/CluckCluckChicken/Magnifier/blob/4a0d26c281946c19bee191ccc86ba3f27d7ee333/Spyglass/Pages/ViewStudio.razor#L68

https://github.com/CluckCluckChicken/Magnifier/blob/4a0d26c281946c19bee191ccc86ba3f27d7ee333/Spyglass/Pages/ViewStudio.razor#L85

https://github.com/CluckCluckChicken/Magnifier/blob/4a0d26c281946c19bee191ccc86ba3f27d7ee333/Spyglass/Pages/ViewProject.razor#L74

https://github.com/CluckCluckChicken/Magnifier/blob/4a0d26c281946c19bee191ccc86ba3f27d7ee333/Spyglass/Pages/ViewProject.razor#L91

https://github.com/CluckCluckChicken/Magnifier/blob/4a0d26c281946c19bee191ccc86ba3f27d7ee333/Spyglass/Services/ReactionService.cs#L26

https://github.com/CluckCluckChicken/Magnifier/blob/4a0d26c281946c19bee191ccc86ba3f27d7ee333/Spyglass/Services/ReactionService.cs#L26

and more

**Comment by FunctionalMetatable** [comment]
...or https://github.com/CluckCluckChicken/Magnifier/search?q=localhost%3A5001

**Comment by CluckCluckChicken** [comment]
will do

**Comment by FunctionalMetatable** [comment]
and you may want to use some environment variables so its easier for people to change it

**Comment by CluckCluckChicken** [comment]
i tried setting up environment variables yesterday and i got them working easily but i didnt notice that i had i thought it wasnt working so i removed them but ill do at some point

**Comment by CluckCluckChicken** [comment]
i also need to use them because storing mongodb connection string and auth token signing key in the docker image itself is messy

**Comment by CluckCluckChicken** [comment]
fixed!
