### ISSUE TITLE
bug: docs dont work

### ISSUE THREAD

**Issue by FunctionalMetatable** [CluckCluckChicken/Magnifier#60]
![image](https://user-images.githubusercontent.com/67440879/120178764-bd342880-c201-11eb-9e26-bb6e498bea9e.png)page-ception

**Comment by CluckCluckChicken** [comment]
i need to put them in a separate repo cos now spyglass is hosted on this one's gh pages

**Comment by FunctionalMetatable** [comment]
> i need to put them in a separate repo cos now spyglass is hosted on this one's gh pages

cant you merge them straight into the blazor app

**Comment by CluckCluckChicken** [comment]
github pages is neat with markdown and i cant figure out how to use most nuget stuff in blazor
