### ISSUE TITLE
Feature Request: add site breaking bugs

### ISSUE THREAD

**Issue by CluckCluckChicken** [CluckCluckChicken/Magnifier#65]
**Feature**

magnifier should barely work properly, be really slow, and not handle errors properly

**Additional context**

https://scratch.mit.edu/discuss/post/5295253/

**Comment by brourbeinsus** [comment]
But why?

**Comment by BarelySmooth** [comment]
Yes, magnifier should return 500 Internal Server Error for all requests

**Comment by CluckCluckChicken** [comment]
there were some but i fixed them i think that counts.
