### ISSUE TITLE
Bug: Wrong authors of comment

### ISSUE THREAD

**Issue by gosoccerboy5** [CluckCluckChicken/Magnifier#68]
**Describe the bug**

When viewing a comment chain, every replier is the same person as the OP
compare these
scratch screenshot
<img width="450" alt="Screen Shot 2021-05-31 at 1 17 57 PM" src="https://user-images.githubusercontent.com/82768218/120229386-a5b16b80-c212-11eb-9c11-a91a2680fded.png">
magnifier screenshot
<img width="450" alt="Screen Shot 2021-05-31 at 1 17 13 PM" src="https://user-images.githubusercontent.com/82768218/120229393-a9dd8900-c212-11eb-95aa-c882c7fb6639.png">

**To Reproduce**

go to a profile page on magnifier, view a comment chain

**Expected behavior**

that the correct people are displayed

**Browser Information**

macOS 11.3, Firefox 88.0.1

**Additional context**

idk but I'm really happy magnifier is released 😄 🥳 🎉

**Comment by CluckCluckChicken** [comment]
fixed!

**Comment by gosoccerboy5** [comment]
That was fast!!!
