### ISSUE TITLE
Bug: I can set the number of reactions to -1

### ISSUE THREAD

**Issue by return-misaPuding** [CluckCluckChicken/Magnifier#69]
**Describe the bug**

When you increase the reactions count and then double-click the same button, the reaction count decreases by 2 instead of 1

**To Reproduce**

1. Find a comment where at least one reaction hasn´t been used yet.
2. click it and increase the count
3. double click it 
4. the reaction count will be -1

**Expected behavior**

The reaction count should be decreased only once

**Browser Information**

Windows 8.1 x64 and Firefox 88.1, but I´m pretty sure this is the page´s issue

**Additional context**

It is probably caused by the toggle requests being handled nearly all at once, so the second one from the second click whether the user already un-toggled the reaction, it´ll see he didn´t so it´ll send the API request to lower the reaction count - at the same time as the request from the first click so the server will receive two requests to lower the reaction and therefore it´ll make the reaction count -1

**Comment by CluckCluckChicken** [comment]
do this to a comment then post the id of that comment pls

**Comment by CluckCluckChicken** [comment]
i think its only client side, since spyglass updates the reaction button, then corrects it after the actual reaction has been updated server side (to make it feel more responsive)

**Comment by gosoccerboy5** [comment]
I cannot reproduce this bug

**Comment by return-misaPuding** [comment]
> 
> 
> i think its only client side, since spyglass updates the reaction button, then corrects it after the actual reaction has been updated server side (to make it feel more responsive)

Yup, this is what I thought

**Comment by gosoccerboy5** [comment]
hehe #69 so funi
