### ISSUE TITLE
settings page

### ISSUE THREAD

**Issue by CluckCluckChicken** [CluckCluckChicken/Magnifier#7]
it needs drip

what should i put in it?

**Comment by CST1229** [comment]
ocular theme

**Comment by CluckCluckChicken** [comment]
E

**Comment by JackyBorderCollie** [comment]
also please include a blury comment from me. aNd AdD sOmE sUsSy ImPoStErS

**Comment by CluckCluckChicken** [comment]
o-o

**Comment by PoIygon** [comment]
Theme for dark and light. Option to not show reply’s and a icon changer so you can change your icon in the top right

**Comment by CluckCluckChicken** [comment]
made a settings page with 1 option that nobody asked for.


> Theme for dark and light. Option to not show reply’s and a icon changer so you can change your icon in the top right

will do
