### ISSUE TITLE
Bug: auth codes can include swears or "censor bypasses"

### ISSUE THREAD

**Issue by CluckCluckChicken** [CluckCluckChicken/Magnifier#71]
auth codes are randomly generated strings, might contain inappropriate language

**Comment by gosoccerboy5** [comment]
Noice

**Comment by return-misaPuding** [comment]
Maybe each second character should be a number so that numbers will be
separated and won't be replaced by XXXXXXXXX and characters will be also
separated so that they won't create a swear word together?

Dne po 31. 5. 2021 21:13 uživatel potatophant ***@***.***>
napsal:

**Comment by CluckCluckChicken** [comment]
it would still be possible for numbers that look like certain letters to be next to other letters creating what looks like swears, maybe a shorter string of numbers like fluffyscratch has? it would be less secure but it wouldnt get people muted

**Comment by Accio1** [comment]
@CluckCluckChicken You could also use exclusively consonants for the codes. All English words have at least one vowel, so not using them could help solve this problem. (Additionally, you could exclude numbers that look like vowels, like 0 or 3).

**Comment by CluckCluckChicken** [comment]
> @CluckCluckChicken You could also use exclusively consonants for the codes. All English words have at least one vowel, so not using them could help solve this problem. (Additionally, you could exclude numbers that look like vowels, like 0 or 3).
thats a good idea, ill look tomorrow.

**Comment by gosoccerboy5** [comment]
> > @CluckCluckChicken You could also use exclusively consonants for the codes. All English words have at least one vowel, so not using them could help solve this problem. (Additionally, you could exclude numbers that look like vowels, like 0 or 3).
> 
> thats a good idea, ill look tomorrow.

is it tomorrow yet

**Comment by CluckCluckChicken** [comment]
it was tomorrow yesterday but i was working on load times which i still havent fixed properly but ill switch back to the main branch and remove consonants from the thingy

**Comment by CluckCluckChicken** [comment]
i seem to have done it yesterday anyway so we can close this
