### ISSUE TITLE
How do you automatically add a header

### ISSUE THREAD

**Issue by PoIygon** [CluckCluckChicken/Magnifier#76]
Currently working on my website using vscode and I was wondering how to automatically add a header

**Comment by CluckCluckChicken** [comment]
magnifier uses a framework called [blazor ](https://dotnet.microsoft.com/apps/aspnet/web-apps/blazor)where its really easy to implement, but if you dont know c# you should try [nuxt ](https://nuxtjs.org/) or [react](https://reactjs.org/). you can also use an iframe or you can make a script with `document.getElementById("view").appendChild(put your header stuff in here)` or something similar and put that script on every page
