### ISSUE TITLE
Feature Request: no

### ISSUE THREAD

**Issue by CluckCluckChicken** [CluckCluckChicken/Magnifier#79]
**Feature**

**Additional context**

**Comment by PoIygon** [comment]
https://scratch.mit.edu/messages/ajax/user-activity/?user=potatophant&max=1000000

**Comment by JackyBorderCollie** [comment]
wow

**Comment by CST1229** [comment]
​

**Comment by CluckCluckChicken** [comment]
i say no

**Comment by JackyBorderCollie** [comment]
make me admin please

**Comment by CluckCluckChicken** [comment]
all admins can do is request 2 endpoints manually to modify the possible reactions rn
