### ISSUE TITLE
Bug: magnifier.potatophant.net is inaccessible

### ISSUE THREAD

**Issue by JackyBorderCollie** [CluckCluckChicken/Magnifier#82]
**Describe the bug**

oMg i wEnT tO oPeN mAgNiFiEr tOdAy aNd iT sHoWeD mE tHiS:
![](https://u.cubeupload.com/JackyBorderCollie/suuuuuuuuuuuuuuuus.png)

**To Reproduce**

help me

**Expected behavior**

i expecting the site to work

**Browser Information**

chrome B)

**Additional context**

it's very sussy because i cannot access it pls help

**Comment by CluckCluckChicken** [comment]
this is more of a technical issue than a bug, since i think its fine for everyone else and the record is probably still propagating in your area. if you wait a while it should work.

**Comment by JackyBorderCollie** [comment]
ok cause i'm in slovak it may take a while

**Comment by CluckCluckChicken** [comment]
potentially

**Comment by JackyBorderCollie** [comment]
omg still inaccessible this is very sussy!11!1!1!1!!

**Comment by CluckCluckChicken** [comment]
SUS!11111 is the Sus Imposter1!1!11111 i forgot to add cname to github actions for the

**Comment by JackyBorderCollie** [comment]
omg yesssssssssss it's working now!1!111!! sus is deactivate!!1!!1!!
