### ISSUE TITLE
Bug: CSS doesn't override browser-default text color

### ISSUE THREAD

**Issue by towerofnix** [CluckCluckChicken/Magnifier#93]
**Describe the bug**

The site CSS doesn't override the browser-default text color in all places it overrides the background (particularly `.bg-white`), meaning if the browser's default is something besides black, the page may have unreadable text.

**To Reproduce**

Set the default browser text color to something besides black; on my computer it's white. Then view e.g. comments on a profile:

![Comments on my profile, viewed in Magnifier. Their white text is nearly impossible to read against the light grey background color.](https://user-images.githubusercontent.com/9948030/120890701-de6a8f80-c5da-11eb-8dcc-06b4ca1d5474.png)

**Expected behavior**

Text should always be readable!

**Browser Information**

N/A. (I'm using Firefox, but I'm pretty sure other browsers let you customize default page colors too.)

**Additional context**

The general fix to avoid running into this kind of issue is to always *also* set text color in the same CSS rules where you set background color. That way, you'll always be declaring a color which is clearly visible against the backdrop, rather than hoping the browser provides one for you.

**Comment by CluckCluckChicken** [comment]
try now.
