### ISSUE TITLE
Feature Request: Clicking avatar in nav bar should bring to profile in Magnifier, not Scratch

### ISSUE THREAD

**Issue by towerofnix** [CluckCluckChicken/Magnifier#94]
**Feature**

Since a user's own profile is probably somewhere that'll be visited pretty frequently (especially e.g. after logging in for the first time), it'd be cool to have the profile picture/avatar in the nav bar open up the comments page for the logged in user!

**Additional context**

Basically the same as #67, but for the nav bar :P

**Comment by JackyBorderCollie** [comment]
I agree, because it would be very epic pog with Magnifier profiles.

**Comment by CluckCluckChicken** [comment]
done, should deploy by a couple of minutes!
